### ISSUE TITLE
Cordova 3.3.0 support

### ISSUE THREAD

**Issue by rreghin** [mkuklis/phonegap-websocket#37]
Is there any chance to add Cordova 3.3.0+ support for you plugin? I just can't make it work, neither if I try to use the 2.x.x version.

I'm doing this (on both Windows and MacOSX):

First:
   Install NodeJS
   Download and install/prepare the Android SDK
   Fix environment PATH (for both nodejs and android sdk)

Then:
   npm install -g cordova
   cd /dev/workspace
   cordova create wstest com.wstest WSTest
   cd wstest
   cordova platform add android
   cordova platform add ios
   cordova plugin add https://github.com/mkuklis/phonegap-websocket
   cordova build

All gets compiled and deployed correctly, but I just can't get the "new WebSocket(...)" to work.

On my index.html I added:

```
    <script>
        if( (typeof(WebSocket) === 'function') || ('WebSocket' in window) ) {
            alert("SUCCESS! Your browser DOES support HTML5 Web Sockets.");
        }
        else {
            alert("Error. Your browser does NOT support HTML5 Web Sockets.");
        }
    </script>
```

Am I doing something wrong?

I also tried to add the code from WebSocket.org's echo test, and it worked on IOS and Android 4.4.x, because both of them have native WebSockets support. But on Android 2.3 and 4.0, just don't work at all. =(

What am I missing??

**Comment by shadimsaleh** [comment]
hello ,
I try to build it at the first I faced an error in building and I solved by it by changing the config.xml to "android-minSdkVersion" value="17"
 but now i can build but when the app is run on emulator i get an error 
anther question how I can send photo or video via this plugin 
thank in advance
