### ISSUE TITLE
why use this vs Socket.IO on phonegap side?

### ISSUE THREAD

**Issue by meta-meta** [mkuklis/phonegap-websocket#55]
Is there a clear performance benefit in using this vs socket.io? I'm brand new to phonegap.

This tutorial says it's trivial to use socket.io 
http://socket.io/socket-io-with-apache-cordova/

is there a need for this plugin if I go that route?

Looking at the demo https://bitbucket.org/mkuklis/phonegap-websocket-demo/src/e6a874f8280900c0273af552c4970232d27c38b5/client/www/index.html?at=master&fileviewer=file-view-default I see socket.io and no reference to this plugin. I'm confused.

**Comment by mkuklis** [comment]
Hey @meta-meta this plugin was created to support web sockets in Android 2.x.x. If you target Android 4.x.x you should be fine without it.
